"""add robot and command_history tables

Revision ID: d2d102a41f6b
Revises:
Create Date: 2025-10-27 03:39:48.401026

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2d102a41f6b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "robots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "command_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("robot_id", sa.Integer(), nullable=False),
        sa.Column("command_string", sa.Text(), nullable=False),
        sa.Column("initial_x", sa.Integer(), nullable=False),
        sa.Column("initial_y", sa.Integer(), nullable=False),
        sa.Column("initial_direction", sa.String(length=10), nullable=False),
        sa.Column("final_x", sa.Integer(), nullable=False),
        sa.Column("final_y", sa.Integer(), nullable=False),
        sa.Column("final_direction", sa.String(length=10), nullable=False),
        sa.Column("stopped_by_obstacle", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"],
            ["robots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("command_history")
    op.drop_table("robots")
    # ### end Alembic commands ###
